---
layout: default
title: 'Action forward is not working if Exception is handled in the Controller&#039;s initialize() phase - Discussion'
---

    <div class="container">
        {% include warning.html %}


<div itemscope itemtype="https://schema.org/Question"><ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><a href="/category/1/mvc">MVC</a></li>
</ol>
<div class="row table-title">
    <div class="col-lg-8 col-md-7 col-sm-6 col-xs-12 wrapper-author">
        <h1 class="" itemprop="name">Action forward is not working if Exception is handled in the Controller&#039;s initialize() phase</h1>
        <div class="visible-xs-block mobile-author">
            <span itemprop="author" itemscope itemtype="https://schema.org/Person"><a href="/user/334/temuri416" class="user-moderator-N"><span itemprop="name">temuri416</span></a></span>
            <time itemprop="dateCreated" datetime="2017-06-29T14:15:40-07:00">Jun '17</time>
        </div>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6 hidden-xs text-right wrapper-stats">
        <table class="table-stats" width="100%">
            <tr style="vertical-align: top;">
                <td>
                    <label>Created</label><br>
                    <time itemprop="dateCreated" datetime="2017-06-29T14:15:40-07:00">Jun '17</time>
                </td>
                <td>
                    <label>Last Reply</label><br>None</td>
                <td>
                    <label>Replies</label><br>
                    <span itemprop="answerCount">0</span>
                </td>
                <td>
                    <label>Views</label><br>902</td>
                <td>
                    <label>Votes</label><br>
                    <span itemprop="upvoteCount">2</span>
                </td>
            </tr>
        </table>
    </div>
</div>
<div class="discussion">
        <div class="row reply-block">
            <div class="col-md-1 col-sm-1 hidden-xs text-center">
                <img src="https://secure.gravatar.com/avatar/1c5a05d695b9e910398795de90197829?s=48&amp;r=pg&amp;d=identicon" class="img-rounded avatar" /><br>
                <span itemprop="author" itemscope itemtype="https://schema.org/Person" class="avatar-name"><a href="/user/334/temuri416" class="user-moderator-N"><span itemprop="name">temuri416</span></a></span>
                <span class="karma">51.3k</span>
            </div>
            <div class="col-md-11 col-sm-11 col-xs-12 post-body"><div class="posts-date hidden-xs" align="right">
        <a name="C16441" href="#C16441">
        <time class="action-date">Jun '17</time>
    </a>
</div>
<div class="post-content"><div><p>Hi all,</p>
<p>I use this approach to handle exceptions thrown in Controller Actions. Nothing fancy here:</p>
<pre><code class="language-php">$eventsManager-&gt;attach('dispatch:beforeException', function($event, $dispatcher, $exception) {
    // Forward to Error controller:
    $dispatcher-&gt;forward([
        'controller' =&gt; 'error',
        'action' =&gt; 'oops',
        'params' =&gt; null,
    ]);
}</code></pre>
<p>Everything works fine if an Exception is thrown inside Controller's Action, i.e. past this line:</p>
<p><a href="https://github.com/phalcon/cphalcon/blob/master/phalcon/dispatcher.zep#L654">https://github.com/phalcon/cphalcon/blob/master/phalcon/dispatcher.zep#L654</a></p>
<p><strong>The problem</strong> is that if an Exception is thrown inside Controller's <code>initialize()</code>, then <strong>forwarding code above does not work</strong> (though it does get executed).</p>
<p>Looking at the code I see something that looks like an oversight to me. This is the code that handles Exception in the named action:</p>
<pre><code class="language-php">try {
    // We update the latest value produced by the latest handler
    let this-&gt;_returnedValue = this-&gt;callActionMethod(handler, actionMethod, params);
} catch \Exception, e {
    if this-&gt;{"_handleException"}(e) === false {
        if this-&gt;_finished === false {
            continue;
        }
    } else {
        throw e;
    }
}</code></pre>
<p>As you can see, an Exception is caught and <code>_handleException</code> is fired inside the dispatch loop, thus giving a chance to <code>forward()</code> to affect execution in subsequent iteration.</p>
<p>And this is how Controller's <code>initialize</code> is called:</p>
<pre><code class="language-php">if wasFresh === true {
    if method_exists(handler, "initialize") {
        handler-&gt;initialize();
    }
    ...
}
</code></pre>
<p>So, if an Exception is thrown in <code>initialize</code>, the error bubbles up and out of the dispatch loop.</p>
<p>So, shouldn't there be a <code>try\catch</code> around the initialize() call as well?</p>
<p>Thanks!</p>
<p>EDIT: Opened <a href="https://github.com/phalcon/cphalcon/issues/12931">this</a> ticket.</p></div>                </div>

                <div class="posts-buttons text-right"><a href="#"  class="btn btn-danger btn-xs" data-cf-modified-4400dd38b8299e51232d5edc-="">
        <span class="glyphicon glyphicon-thumbs-down"></span></a>
    <a href="#"  class="btn btn-success btn-xs" data-cf-modified-4400dd38b8299e51232d5edc-="">
        <span class="glyphicon glyphicon-thumbs-up"></span><span itemprop="upvoteCount">2</span></a></div>
            </div>
        </div><div class="row"><div class="col-md-1 small" align="center"></div>
        <div class="col-md-11 login-comment">
            
        </div></div>
</div><input type="hidden" id="post-id" name="post-id" value="16441" /><div id="suggested-posts"></div>
    <div id="sticky-progress" style='display:none'></div>
</div>
    </div>